import Head from "next/head";
import React from "react";
import { api } from "@/utils/api";
import Navbar from "@/components/common/Navbar";
import styles from "@/styles/Home.module.scss";
import { useRouter } from "next/router";
import { useCheckAuth } from "@/hooks/useCheckAuth";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { loading } = useCheckAuth();
  const router = useRouter();

  if (loading) return <div style={{ display: "none" }}></div>;

  return (
    <>
      <Head>
        <title>Query Flex</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <section
          className={`prose flex md:container lg:prose-xl md:mx-auto ${styles.homeMain}`}
        >
          <h1 className={`justify-center ${styles.header}`}>QueryFlex</h1>
          <p className={`${styles.subheader}`}>
            MultiDB <span className={styles.special}>QueryFlex</span> is an
            all-in-one Database Query Generator designed for developers working
            with various database systems!
          </p>
          <div>
            <button
              onClick={() => router.push("/auth/sign-up")}
              className={`btn btn-success glass btn-outline m-3 sm:btn-sm md:btn-md lg:btn-lg ${styles.getStarted}`}
            >
              Get Started
            </button>
            <button
              className={`btn btn-info glass btn-outline m-3 sm:btn-sm md:btn-md lg:btn-lg ${styles.getStarted}`}
            >
              Request Demo
            </button>
          </div>
        </section>
      </>
    </>
  );
}
