import Head from "next/head";
import { api } from "@/utils/api";
import HomePage from "./home";
import Navbar from "@/components/common/Navbar";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Query Flex</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <section
          className={`prose flex justify-center md:container lg:prose-xl md:mx-auto ${styles.homeMain}`}
        >
          <h1 className={`justify-center ${styles.header}`}>Query Flex</h1>
        </section>
      </>
    </>
  );
}
